- name: Install K3s Worker Nodes
  hosts: workers
  become: yes
  vars_files:
    - ../group_vars/all/vars.yml
  vars:
    k3s_version: "v1.28.5+k3s1"
    k3s_token: "{{ vault_k3s_token }}"
    k3s_server_url: "https://192.168.0.12:6443"
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
        state: present

    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Install K3s agent
      shell: |
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_TOKEN="{{ k3s_token }}" \
        K3S_URL="{{ k3s_server_url }}" \
        sh /tmp/k3s-install.sh
      environment:
        INSTALL_K3S_EXEC: "agent"
      args:
        creates: /usr/local/bin/k3s

    - name: Start and enable K3s agent service
      systemd:
        name: k3s-agent
        state: started
        enabled: yes
        daemon_reload: yes