---
all:
  children:
    control_plane:
      hosts:
        k3s-control-plane-01:
          ansible_host: 192.168.0.12
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    workers:
      hosts:
        k3s-worker-01:
          ansible_host: 192.168.0.13
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        k3s-worker-02:
          ansible_host: 192.168.0.14
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa